//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Demo.DataModels
{
    using POS_Demo.DataModels.Common;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment_Types : AuditableEntity
    {
        
        public Comment_Types()
        {
            this.Comments = new HashSet<Comment>();
        }

        [Display(Name = "Comment Type Code")]
        [DisplayFormat(DataFormatString = "{0:D5}", ApplyFormatInEditMode = true)]
        public int Id { get; set; }

        [Display(Name = "Comment Type Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
    
        
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
