//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Demo.DataModels
{
    using POS_Demo.DataModels.Common;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment : AuditableEntity
    {
        [Display(Name = "Comment Code")]
        [DisplayFormat(DataFormatString = "{0:D5}", ApplyFormatInEditMode = true)]
        public int Id { get; set; }

        [Display(Name = "Comment")]
        public string Comment1 { get; set; }

        [Display(Name = "Comment Type")]
        public int FK_Comment_TypeId { get; set; }


        public int Comment_For_Id { get; set; }
    
        public virtual Comment_Types Comment_Types { get; set; }
    }
}
