//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Demo.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment : Common.AuditableEntity
    {
        public int Id { get; set; }
        public string Comment1 { get; set; }
        public Nullable<int> FK_Comment_TypeId { get; set; }
        public int Comment_For_Id { get; set; }
    
        public virtual Comment_Types Comment_Types { get; set; }
    }
}
