//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Demo.DataModels
{
    using POS_Demo.DataModels.Common;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Developer : AuditableEntity
    {

        public Developer()
        {
            this.Units_Details = new HashSet<Units_Details>();
        }

        [Display(Name = "Developer Code")]
        [DisplayFormat(DataFormatString = "{0:D5}", ApplyFormatInEditMode = true)]
        public int Id { get; set; }

        [Display(Name = "Developer Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }


        public virtual ICollection<Units_Details> Units_Details { get; set; }
    }
}
