//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Demo.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSEntities : DbContext
    {
        public POSEntities()
            : base("name=POSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment_Types> Comment_Types { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Deal_Source> Deal_Source { get; set; }
        public virtual DbSet<Deal_Status> Deal_Status { get; set; }
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<Sales_Person> Sales_Person { get; set; }
        public virtual DbSet<Sales_Person_Slab> Sales_Person_Slab { get; set; }
        public virtual DbSet<Units_Details> Units_Details { get; set; }
        public virtual DbSet<Units_Payments> Units_Payments { get; set; }
        public virtual DbSet<Units_Status> Units_Status { get; set; }
    }
}
