//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Demo.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units_Status
    {
        public int Id { get; set; }
        public int FK_Units_DetailsId { get; set; }
        public int FK_Deal_StatusId { get; set; }
        public int FK_Deal_SourceId { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Deal_Source Deal_Source { get; set; }
        public virtual Deal_Status Deal_Status { get; set; }
        public virtual Units_Details Units_Details { get; set; }
    }
}
