//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Demo.DataModels
{
    using POS_Demo.DataModels.Common;
    using System;
    using System.Collections.Generic;
    
    public partial class Units_Payments : AuditableEntity
    {
        public int Id { get; set; }
        public int FK_Units_DetailsId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal PaymentAmountPercentage { get; set; }
        public decimal CommissionDeduction { get; set; }
        public decimal SalesPersonCommision { get; set; }
        public decimal NetAmountDue { get; set; }
        public decimal UncollectedPercentage { get; set; }
    
        public virtual Units_Details Units_Details { get; set; }
    }
}
