//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Demo.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Units_Details()
        {
            this.Sales_Person_Slab = new HashSet<Sales_Person_Slab>();
            this.Units_Payments = new HashSet<Units_Payments>();
            this.Units_Status = new HashSet<Units_Status>();
        }
    
        public int Id { get; set; }
        public System.DateTime SaleDate { get; set; }
        public Nullable<int> FK_DeveloperId { get; set; }
        public string Unit_NO { get; set; }
        public decimal Unit_Volume { get; set; }
        public int FK_Sales_PersonId { get; set; }
        public decimal Deal_Slab { get; set; }
        public decimal Commission_Amount { get; set; }
        public Nullable<decimal> Commission_Deduction { get; set; }
        public decimal Total_Commission { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual Sales_Person Sales_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Person_Slab> Sales_Person_Slab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Units_Payments> Units_Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Units_Status> Units_Status { get; set; }
    }
}
